twig:
    default_path: '%kernel.project_dir%/templates'
    # les fichiers de themes de formulaire se trouve dans vendor/symfony/twig-bridge/ressources/view/form
    form_themes: ['bootstrap_5_layout.html.twig']

when@test:
    twig:
        strict_variables: true
